spring:  datasource:    password: jeep    username: jeep    url: jdbc:mysql://localhost:3306/jeep#    points to mysql database



logging:
  level:
    root: warn
    '[com.promineotech]': debug